name: UIandUnitTests

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        pod repo update
        pod install
        
    #- name: Test
    #  run: xcodebuild -workspace Logging.xcworkspace -scheme "Logging"  -destination 'platform=iOS Simulator,name=iPad Pro (9.7-inch),OS=14.0' test
    - name: Archive
      run: xcodebuild -workspace Logging.xcworkspace -scheme "Logging" -sdk iphoneos -allowProvisioningUpdates -configuration AppStoreDistribution archive -archivePath $PWD/build/Logging.xcarchive
    - name: Export
      run: xcodebuild -exportArchive -archivePath $PWD/build/Logging.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
      
    - name: NowSecure Platform Integration
      uses: blawrencens/nowsecure-actions-integration@1.0.2
      with:
        # Please provide the path for the app to be uploaded
        app-path: "/build/Logging.ipa"
        # Please provide the API Key for NowSecure Platform
        api-key: ${{ secrets.PLATFORM_API_KEY }}
        # Please provide the Group Id of the application being integrated, using Tron group
        group-id: "e01d876f-dffd-4beb-91ac-145459657511"
