name: UIandUnitTests

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        pod repo update
        pod install
        
    - name: Test
      run: xcodebuild -workspace Logging.xcworkspace -scheme "Logging"  -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.7' test

